mapbender_configuratorbundle:
    resource: '@MapbenderConfiguratorBundle/Controller/'
    type: annotation
mapbender_start:
    path: /
    defaults: { _controller: 'MapbenderCoreBundle:Welcome:list' }
mapbender_corebundle:
    resource: '@MapbenderCoreBundle/Controller/'
    type: annotation
mapbender_managerbundle:
    resource: '@MapbenderManagerBundle/Controller/'
    type: annotation
fom_managerbundle:
    resource: '@FOMManagerBundle/Controller'
    type: annotation
fom_userbundle:
    resource: '@FOMUserBundle/Controller'
    type: annotation
ows_corebundle:
    resource: '@OwsProxy3CoreBundle/Controller/'
    prefix: /owsproxy
    type: annotation
fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'
mapbender_datasourcebundle:
    type: annotation
    resource: '@MapbenderDataSourceBundle/Controller/'
